export const streamers = [
    { name : "2fun", pp : "2fun.png", dgs : [], jackpot : ""},
    { name : "Solskin__", pp : "solskin__.jpg", dgs : [], jackpot : ""},
    { name : "Noleler", pp : "noleler.png", dgs : [], jackpot : ""},
    { name : "El_Camel", pp : "el_camel.png", dgs : [], jackpot : ""},
    { name : "RacletteOVNI", pp : "racletteOVNI.jpg", dgs : [], jackpot : ""},
    { name : "Aoi_Kayou", pp : "aoi_kayou.png", dgs : [], jackpot : ""},
    { name : "Ayatrindade", pp : "ayatrindade.jpg", dgs : [], jackpot : ""},
    { name : "Geekanort", pp : "geekanort.png", dgs : ["geekanort_1.png", "geekanort_2.png"], jackpot : "https://streamlabscharity.com/api/v1/users/campaigns/geekanort/les-poussins-solidaires-2025-geekanort"},
    { name : "Ryste", pp : "ryste.png", dgs : [], jackpot : ""},
    { name : "HugoRLT", pp : "hugoRLT.png", dgs : [], jackpot : ""},
    { name : "PikoTV", pp : "pikoTV.jpg", dgs : [], jackpot : ""},
    { name : "Titeka", pp : "titeka.png", dgs : ["titeka.png"], jackpot : ""},
    { name : "Ben_Momentum", pp : "ben_momentum.png", dgs : [], jackpot : ""},
    { name : "Divarine_", pp : "divarine_.png", dgs : [], jackpot : ""},
    { name : "SekkarouTV", pp : "sekkarouTV.png", dgs : [], jackpot : ""},
    { name : "Kusapedia", pp : "kusapedia.png", dgs : [], jackpot : ""},
    { name : "Cardealia", pp : "cardealia.png", dgs : [], jackpot : ""},
    { name : "Clem_Brule", pp : "clem_brule.jpg", dgs : [], jackpot : ""},
    { name : "Sinistrosss", pp : "sinistrosss.jpg", dgs : [], jackpot : ""},
    { name : "Kaisha007", pp : "kaisha007.png", dgs : [], jackpot : ""},
    { name : "SebastoS", pp : "sebastoS.png", dgs : [], jackpot : ""},
    { name : "Eda69", pp : "eda69.png", dgs : [], jackpot : ""},
    { name : "Izzouille_", pp : "izzouille_.jpg", dgs : [], jackpot : ""},
    { name : "Remyx_", pp : "remyx_.jpg", dgs : [], jackpot : ""},
    { name : "AsunyanTV", pp : "asunyanTV.png", dgs : [], jackpot : ""},
    { name : "NioWolfs", pp : "niowolfs.png", dgs : ["niowolfs.jpg"], jackpot : ""},
    { name : "RandyComicsFR", pp : "randycomicsFR.png", dgs : ["randycomic.png"], jackpot : ""},
    { name : "Maeenn_", pp : "maeenn_.png", dgs : [], jackpot : ""},
    { name : "Katinckaa", pp : "katinckaa.png", dgs : [], jackpot : ""},
    { name : "Gwendyana", pp : "gwendyana.jpg", dgs : [], jackpot : ""},
    { name : "Saint_Seraphina", pp : "saint_seraphina.png", dgs : [], jackpot : ""},
    { name : "HerrCule", pp : "herrcule.png", dgs : [], jackpot : ""},
    { name : "Acengel", pp : "", dgs : [], jackpot : ""},
]