export const streamers = [
    { name : "2fun", pp : "2fun.png", dgs : []},
    { name : "Solskin__", pp : "solskin__.jpg", dgs : []},
    { name : "Noleler", pp : "noleler.png", dgs : []},
    { name : "El_Camel", pp : "el_camel.png", dgs : []},
    { name : "RacletteOVNI", pp : "racletteOVNI.jpg", dgs : []},
    { name : "Aoi_Kayou", pp : "aoi_kayou.png", dgs : []},
    { name : "Ayatrindade", pp : "ayatrindade.jpg", dgs : []},
    { name : "Geekanort", pp : "geekanort.png", dgs : ["geekanort_1.png", "geekanort_2.png"]},
    { name : "Ryste", pp : "ryste.png", dgs : []},
    { name : "HugoRLT", pp : "hugoRLT.png", dgs : []},
    { name : "PikoTV", pp : "pikoTV.jpg", dgs : []},
    { name : "Titeka", pp : "titeka.png", dgs : []},
    { name : "Ben_Momentum", pp : "ben_momentum.png", dgs : []},
    { name : "Divarine_", pp : "divarine_.png", dgs : []},
    { name : "SekkarouTV", pp : "sekkarouTV.png", dgs : []},
    { name : "Kusapedia", pp : "kusapedia.png", dgs : []},
    { name : "Cardealia", pp : "cardealia.png", dgs : []},
    { name : "Clem_Brule", pp : "clem_brule.jpg", dgs : []},
    { name : "Sinistrosss", pp : "sinistrosss.jpg", dgs : []},
    { name : "Kaisha007", pp : "kaisha007.png", dgs : []},
    { name : "SebastoS", pp : "sebastoS.png", dgs : []},
    { name : "Eda69", pp : "eda69.png", dgs : []},
    { name : "Izzouille_", pp : "izzouille_.jpg", dgs : []},
    { name : "Remyx_", pp : "remyx_.jpg", dgs : []},
    { name : "AsunyanTV", pp : "asunyanTV.png", dgs : []},
    { name : "NioWolfs", pp : "niowolfs.png", dgs : []},
    { name : "RandyComicsFR", pp : "randycomicsFR.png", dgs : []},
    { name : "Maeenn_", pp : "maeenn_.png", dgs : []},
]